language: cpp
before_install:
  -
    if [ ${PACKAGE} = clang-3.4 ];
    then
      sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main";
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
    fi
  - export CC=${REAL_CC}
  - export CXX=${REAL_CXX}
install:
  -
    if [ -n "$PPA" ]; then
      sudo add-apt-repository --yes ${PPA};
    fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${PACKAGE}
  - sudo apt-get install -qq libgtest-dev
before_script:
  - echo check version
  - ${CC} --version
  - ${CXX} --version
  -
    if [ ${PACKAGE} = clang-3.1 ];
    then
      wget http://clang.llvm.org/libstdc++4.6-clang11.patch;
      sudo patch /usr/include/c++/4.6/type_traits < libstdc++4.6-clang11.patch;
    fi
script:
  - cd ./test
  - make
  - make test
env:
  - ignore=this
matrix:
  exclude:
    - env: ignore=this
  include:
    - compiler: clang
      env: REAL_CC=clang-3.1 REAL_CXX=clang++-3.1 PPA=ppa:h-rayflood/llvm         PACKAGE=clang-3.1
    - compiler: clang
      env: REAL_CC=clang-3.2 REAL_CXX=clang++-3.2 PPA=ppa:h-rayflood/llvm         PACKAGE=clang-3.2
    - compiler: clang
      env: REAL_CC=clang-3.3 REAL_CXX=clang++-3.3 PPA=ppa:h-rayflood/llvm         PACKAGE=clang-3.3
    - compiler: clang
      env: REAL_CC=clang     REAL_CXX=clang++-3.4 PPA=                            PACKAGE=clang-3.4
    - compiler: gcc
      env: REAL_CC=gcc-4.6   REAL_CXX=g++-4.6     PPA=                            PACKAGE=g++-4.6
    - compiler: gcc
      env: REAL_CC=gcc-4.7   REAL_CXX=g++-4.7     PPA=ppa:ubuntu-toolchain-r/test PACKAGE=g++-4.7
    - compiler: gcc
      env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PPA=ppa:ubuntu-toolchain-r/test PACKAGE=g++-4.8
