
DIRS=./breadth_first_search

all:
	for dir in $(DIRS); do \
		cd $$dir && make ; \
	done

clean:
	for dir in $(DIRS); do \
		cd $$dir && make clean ; \
	done

test:
	for dir in $(DIRS); do \
		cd $$dir && make test ; \
	done

